<?php

/**
 * @file
 * Contains breakpoints_settings.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function breakpoints_settings_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the breakpoints_settings module.
    case 'help.page.breakpoints_settings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Breakpoints Settings') . '</p>';
      return $output;

    default:
  }
}

function breakpoints_settings_page_attachments(array &$page) {
  // Grabbing all breakpoint groups by provider
  $groups = \Drupal::service('breakpoint.manager')->getGroups();
  $js_breakpoints = array();

  if (!empty($groups)) {
    // Run through all group breakpoints and load them.
    foreach ($groups as $group_id => $group) {
      $breakpoints = \Drupal::service('breakpoint.manager')->getBreakpointsByGroup($group_id);
      foreach ($breakpoints as $id => $breakpoint) {
        // Todo remove combine.
        $labels [] = $breakpoint->getLabel();
        $medias [] = $breakpoint->getMediaQuery();
        $combine = array_combine($labels, $medias);
        // Nest breakpoints by group with the label as key and query as value.
        $js_breakpoints[$group_id] = $combine;
      }
      $page['#attached']['drupalSettings']['breakpoints_settings'] = $js_breakpoints;
    }
  }
}
